name: markd
version: 0.8.1
authors:
- David Peek <ninjascript@gmail.com>
- Tom Yeh <tomyeh@rikulo.org>
description: A fork of dart-markdown for easy customizing markdown syntaxes.
homepage: https://github.com/tomyeh/markd
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  test: '^0.12.4+1'
dependencies:
  rikulo_commons: ">=2.0.0"
